using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;

namespace LinqToTextFiles
{
    internal static class Client
    {
        private static string[] LinesFromTxt;

        static Client()
        {
            LinesFromTxt = File.ReadAllLines("DummyData.csv");
        }

        public static void Main()
        {

            //Poi: Note the 'TSource' in 2nd 'Select' where 'Publisher' objects are being created. Here input is IEnumerable<string> which is
            //the output from 1st Select where TResult is generated by '.Split'

            IEnumerable<Publisher> filteredLines = LinesFromTxt
                .Where<string>(line => !line.StartsWith("#"))
                .Select<string, IEnumerable<string>>(line => line.Split(','))
                .Select<IEnumerable<string>, Publisher>(info => new Publisher { Isbn = (info as string[])[0], Title = (info as string[])[1] });

            filteredLines.IterateOverSequence<Publisher>();
        }

        private static void IterateOverSequence<T>(this IEnumerable<T> source)
        {
            try
            {
                Console.WriteLine();
                foreach(T item in source)
                {
                    Console.WriteLine(item);
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        private class Publisher
        {
            public String Isbn {get; set;}
            public String Title {get; set;}

            public override string ToString() => "Isbn => " + Isbn + "\tTitle => " + Title;
        }
    }
}