// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameOnlineCourseToOnlineCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameOnlineCourseToOnlineCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051513401_Rename-Online-Course-To-OnlineCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
