// <auto-generated />
namespace Ch_11.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inititem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inititem));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081317246_init-item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
