// <auto-generated />
namespace Ch_Two.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Init2152018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init2152018));
        
        string IMigrationMetadata.Id
        {
            get { return "201802141810276_Init-2-15-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
