//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venkat___Entity_Framework.Tut.Part_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentMF
    {
        public DepartmentMF()
        {
            this.Employees = new HashSet<EmployeeMF>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmployeeMF> Employees { get; set; }
    }
}
