// <auto-generated />
namespace EF_102.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init992017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init992017));
        
        string IMigrationMetadata.Id
        {
            get { return "201709090712163_Init-992017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
